### Imports

In [1]:
import cv2
import numpy as np
import glob

In [2]:
# print("Opencv:", cv2.__version__)
# img = np.zeros((120, 400, 3), dtype=np.uint8)
# cv2.putText(img, "Opencv2 OK", (10, 80), cv2.FONT_HERSHEY_SIMPLEX, 2, (255,255,255), 3)
# # If you installed a non-headless build, you can display a window:
# cv2.imshow("hello", img)
# cv2.waitKey(0)
# # Always safe (headless or not): save to file
# cv2.imwrite("hello.png", img)

In [12]:
# termination criteria
criteria = (cv2.TERM_CRITERIA_EPS + cv2.TERM_CRITERIA_MAX_ITER, 30, 0.001)
 
# prepare object points, like (0,0,0), (1,0,0), (2,0,0) ....,(6,5,0)
objp = np.zeros((10*7,3), np.float32)
objp[:,:2] = np.mgrid[0:10,0:7].T.reshape(-1,2)
 
# Arrays to store object points and image points from all the images.
objpoints = [] # 3d point in real world space
imgpoints = [] # 2d points in image plane.
 
images = glob.glob('*.jpg')
 
for fname in images:
    img = cv2.imread(fname)
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
 
    # Find the chess board corners
    ret, corners = cv2.findChessboardCorners(gray, (10,7), None)
 
    # If found, add object points, image points (after refining them)
    if ret == True:
        objpoints.append(objp)
 
        corners2 = cv2.cornerSubPix(gray,corners, (11,11), (-1,-1), criteria)
        imgpoints.append(corners2)
 
        # Draw and display the corners
        cv2.drawChessboardCorners(img, (10,7), corners2, ret)
        cv2.imshow('img', img)
        cv2.waitKey(2000)
 
cv2.destroyAllWindows()

In [ ]:
# # Open the default webcam (0)
# cap = cv2.VideoCapture(0)
 
# # Check if the webcam was opened successfully
# if not cap.isOpened():
#         print("Error: Could not access the webcam.")
# else:
#         print("Webcam accessed successfully!")

# while True:
    
    
#     # Read the first frame to confirm capturing
#     ret, frame = cap.read()

#     if not ret:
#         print("Error: Could not capture a frame.")
#         break

#     cv2.imshow('Video', frame)
#     if cv2.waitKey(1) == ord('q'):
#         break
 
# # Release the webcam
# cap.release()
# cv2.destroyAllWindows()

Webcam accessed successfully!


In [3]:
cap = cv2.VideoCapture(0)

while True:
    ret, frame = cap.read()
    cv2.imshow("Calibration", frame)

    key = cv2.waitKey(1)

    if key == ord('s'):
        cv2.imwrite("calib_%d.jpg" % np.random.randint(1000), frame)

    if key == ord('q'):
        break
cap.release()
cv2.destroyAllWindows()

In [2]:
criteria = (cv2.TERM_CRITERIA_EPS + cv2.TERM_CRITERIA_MAX_ITER, 30, 0.001)

objp = np.zeros((10*7,3), np.float32)
objp[:,:2] = np.mgrid[0:10,0:7].T.reshape(-1,2)

square_size = 0.022
objp *= square_size

objpoints = []
imgpoints = []

images = glob.glob('calib_*.jpg')

for fname in images:
    img = cv2.imread(fname)
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

    ret, corners = cv2.findChessboardCorners(gray, (10,7), None)

    if ret:
        objpoints.append(objp)

        corners2 = cv2.cornerSubPix(gray, corners, (11, 11), (-1, -1), criteria)
        imgpoints.append(corners2)

        cv2.drawChessboardCorners(img, (10,7), corners2, ret)
        cv2.imshow('img', img)
        cv2.waitKey(1000)
cv2.destroyAllWindows()

In [3]:
ret, mtx, dist, rvecs, tvecs = cv2.calibrateCamera(
    objpoints,
    imgpoints,
    gray.shape[::-1],
    None,
    None
)

print(mtx, dist, rvecs, tvecs)

[[1.72899891e+03 0.00000000e+00 3.00531611e+02]
 [0.00000000e+00 1.68734801e+03 2.31839933e+02]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00]] [[ 5.08616111e-01 -1.59643615e+01  9.79763999e-02 -2.04584574e-02
   6.13169381e+02]] (array([[-0.30213167],
       [-0.24743339],
       [-1.65136332]]), array([[-0.12202953],
       [-0.44758762],
       [-1.41118715]]), array([[-0.5093498 ],
       [-0.34257674],
       [-1.43184541]]), array([[ 0.20488485],
       [-0.16936377],
       [-1.6144718 ]]), array([[-0.21341743],
       [ 0.14396952],
       [-1.44671881]]), array([[ 0.10066529],
       [-0.24525533],
       [-1.56123509]]), array([[ 0.20064977],
       [-0.1885849 ],
       [-1.24405072]]), array([[ 0.35191573],
       [-0.07426257],
       [-1.86523212]]), array([[ 0.15944219],
       [-0.16856518],
       [-1.51928695]])) (array([[-0.16710061],
       [ 0.05263463],
       [ 3.33128332]]), array([[-0.05072458],
       [-0.07400477],
       [ 2.50581174]]), array([[-0.18099807

In [4]:
aruco_dict = cv2.aruco.getPredefinedDictionary(
    cv2.aruco.DICT_4X4_50
)

corners, ids, rejected = cv2.aruco.detectMarkers(
    frame,
    aruco_dict
)

# retval, rvec, tvec = cv2.aruco.estimatePoseSingleMarkers(
#     corners,
#     marker_length,
#     mtx,
#     dist
# )

AttributeError: module 'cv2.aruco' has no attribute 'detectMarkers'

In [5]:
print(cv2.__version__)

4.13.0
