In [1]:
import cv2
import numpy as np
import time
from sympy import symbols, cos, sin, Matrix
from pymycobot.mycobot import MyCobot
from scipy.spatial.transform import Rotation as R

START_POS = [0,0,0,0,0,0]
NEUTRAL = [0, -40, 55, 0, 30, 0]
WATCHING_POS = [88.3, 0, 150, -180, 46.5, -180]
bot = MyCobot('/dev/ttyACM0', 115200)

try:
    mtx = np.array(np.loadtxt('calibration/calib_mtx.csv', delimiter=','))
    dist = np.array(np.loadtxt('calibration/calib_dist.csv', delimiter=','))
except FileNotFoundError:
    print('Files not found, make sure you ran calibration!')

aruco_dict = cv2.aruco.getPredefinedDictionary(
    cv2.aruco.DICT_4X4_50
)

# detector = cv2.aruco.ArucoDetector(aruco_dict)

tagSize = 38 / 1000 # m

def drawSquare(frame, corners):
    for i in range(4):
        cv2.line(frame, (int(corners[0][i][0]),int(corners[0][i][1])), (int(corners[0][(i+1)%4][0]), int(corners[0][(i+1)%4][1])), (0,0,255), 3)

def trans(a, alpha, d, theta):
    return Matrix([
        [cos(theta), -sin(theta), 0, a],
        [sin(theta)*cos(alpha), cos(theta)*cos(alpha), -sin(alpha), -sin(alpha)*d],
        [sin(theta)*sin(alpha), cos(theta)*sin(alpha), cos(alpha), cos(alpha)*d],
        [0, 0, 0, 1]
    ])

qs = symbols('q1:7')
q1, q2, q3, q4, q5, q6 = qs
l0, l1, l2, l3, l4, l5 = [114, 0, 100, 97, 0, 56] # mm
alpha2, alpha4, alpha5, alpha6 = np.radians([-90, -90, 90, -90]) # rad

l3_off = 10 #mm
j2_off = np.radians(-90) # rad

dh = [
    [0, 0, l0, q1],
    [0, alpha2, l1, q2 + j2_off],
    [l2, 0, 0, q3],
    [l3_off, alpha4, l3, q4],
    [0, alpha5, l4, q5],
    [0, alpha6, l5, q6]

    # [0, 0, 112, q1],
    # [0, -90, 0, q2],
    # [108, 0, 0, q3],
    # [10, -90, 95, q4],
    # [0, 90, 0, q5],
    # [0, -90, 57, q6]
]

T_ew = Matrix.eye(4)
for row in dh:
    T_ew *= trans(*row)

T_ec = np.array([
    [0, 0, 1, -15],
    [-1, 0, 0, -45],
    [0, -1, 0, 0],
    [0, 0, 0, 1]
])

Note: This class is no longer maintained since v3.6.0, please refer to the project documentation: https://github.com/elephantrobotics/pymycobot/blob/main/README.md


In [2]:
R_ew = T_ew[0:3, 0:3]
t_ew = T_ew[0:3, 3]
T_we = Matrix.eye(4)
T_we[0:3, 0:3] = R_ew.T
T_we[0:3, 3] = -R_ew.T @ t_ew

In [4]:
bot.send_angles(START_POS, 40)
time.sleep(2)
bot.set_gripper_value(95, 40, 1)
time.sleep(2)
bot.send_angles(NEUTRAL, 40)
time.sleep(2)

In [16]:
cv2.destroyAllWindows()
cv2.waitKey(1)

cap = cv2.VideoCapture(1)
while True:
    ret, frame = cap.read()
    if (not ret): continue

    # corners, ids, _ = detector.detectMarkers(frame)
    corners, ids, _ = cv2.aruco.detectMarkers(frame, aruco_dict)

    objpoints = np.array([
        (-tagSize/2, tagSize/2, 0),
        (tagSize/2, tagSize/2, 0),
        (tagSize/2, -tagSize/2, 0),
        (-tagSize/2, -tagSize/2, 0)
    ])

    key = cv2.waitKey(1)

    if corners is not None and ids is not None:
        for square, id in zip(corners, ids):
            drawSquare(frame, square)
            ret, rvec, tvec = cv2.solvePnP(objpoints, square[0], mtx, dist)
            distance = np.linalg.norm(tvec) 
            t_rounded = np.round(tvec * 1000, 2).flatten().tolist()
            text = ", ".join(map(str, t_rounded))

            cv2.putText(frame, '%f mm' % (distance * 1000), (int(square[0][0][0]), int(square[0][0][1])), cv2.FONT_HERSHEY_COMPLEX, 1, (60,255,70), 2)
            cv2.putText(frame, text, (int(square[0][0][0]), int(square[0][0][1]) + 20), cv2.FONT_HERSHEY_COMPLEX, 0.5, (255,255,255), 2)

            cv2.drawFrameAxes(frame, mtx, dist, rvec, tvec, tagSize * 1.5, 2)
    

    if key == ord(' '):
        bot_angles = bot.get_angles()
        joint_angles = [np.radians(j) for j in (bot_angles if (bot_angles is not None and bot_angles != -1) else NEUTRAL)]
        T_sub = T_ew.subs(zip([q1, q2, q3, q4, q5, q6], joint_angles)).evalf()
        T_sub = np.array(T_sub).astype(np.float64)

        wp_ee = bot.get_coords()
        if wp_ee == -1:
            wp_ee = WATCHING_POS
        
        R_co = cv2.Rodrigues(rvec)[0]
        T_co = np.eye(4)
        T_co[:3,:3] = R_co
        T_co[:3,3] = tvec.flatten() * 1000

        T_wo = T_sub @ T_ec @ T_co
        
        # cp_obj = tvec.flatten() * 1000
        # ep_obj = T_ec @ np.concatenate((cp_obj, [1]))
        wp_obj = T_wo[:3, 3]
        R_wo = T_wo[:3, :3]
        cube_x = R_wo[:, 0]
        w_yaw = np.degrees(np.arctan2(cube_x[1], cube_x[0]))
        w_yaw = ((w_yaw + 45) % 90) - 45

        des_pos = np.concatenate((wp_obj, [-160, 90, -160 + w_yaw]))

        # des_pos = wp_ee + np.concatenate((wp_obj[:3], [0,90-wp_ee[4],0]))
        # obj = T_sub @ (T_ec @ tvec_4)
        # ee_pos = np.concatenate((obj[:3], [-160, 90, -160]))
        print('EE: ', wp_ee)
        print('rvec: ', R_co)
        # print('rxyz: ', r.as_euler('XYZ', degrees=True))
        # print('z_off: ', np.degrees(z_off))
        print('tvec: ', np.concatenate((tvec.flatten() * 1000, [1])).tolist())
        # print('obj in ee: ', ep_obj.tolist())
        print('obj: ', wp_obj)
        print('des: ', des_pos)
        # bot.send_coords(np.concatenate((wp_obj[:-1], [-160, 90, -160])), 40)
        des_pos[1] += 45
        des_pos[2] += 125
        bot.send_coords(des_pos, 40)
        time.sleep(2)
        # des_pos[2] -= 75
        # bot.send_coords(des_pos, 40)
        # time.sleep(2)
        # bot.set_gripper_value(70, 40)
        # time.sleep(2)
        # bot.send_angles(START_POS, 40)
 
    cv2.imshow('ArUco', frame)

    if key == ord('r'):
        bot.set_gripper_value(95, 40, 1)
        time.sleep(2)
        bot.send_angles(NEUTRAL, 40)
        time.sleep(2)

    if key == ord('q'):
        break

cap.release()
cv2.destroyAllWindows()
cv2.waitKey(1) 

EE:  [86.2, 0.5, 145.5, -178.21, 43.12, -177.28]
rvec:  [[ 0.97816053 -0.20613576  0.0266463 ]
 [-0.14728868 -0.77788638 -0.61090001]
 [ 0.14665613  0.59363358 -0.79125922]]
tvec:  [-31.541287714042916, 8.421923325876348, 160.35918743115084, 1.0]
obj:  [170.35153674  18.9270725  238.09397028]
des:  [ 170.35153674   18.9270725   238.09397028 -160.           90.
 -170.49891461]


-1

In [16]:
bot.get_angles()

In [76]:
T_sub[0:3, 3] = [0,0,0]

In [11]:
type(cube_x)

sympy.matrices.dense.MutableDenseMatrix

In [88]:
T_sub ** -1

Matrix([
[   0.691674064123896, 0.00393154867452358,  0.722199094393889,   0],
[-0.00598333549845576,  -0.999919669059459, 0.0111738589724029,   0],
[    0.72218501003181, -0.0120498279258288, -0.691594977521028,   0],
[                   0,                   0,                  0, 1.0]])

In [4]:
from scipy.spatial.transform import Rotation as R

In [7]:
r = R.from_matrix(T_sub[0:3,0:3])
r.as_euler('xyz', degrees=True)

array([117.34787818,  42.05717001, -24.08295894])

In [24]:
        R_co = cv2.Rodrigues(rvec)[0]
        T_co = np.eye(4)
        T_co[:3,:3] = R_co
        T_co[:3,3] = tvec.flatten() * 1000

        T_wo = T_sub @ T_ec @ T_co